all:
  children:
    label_studio:
      hosts:
        label_studio_server:
          ansible_host: i-0156aaa6cd18f4f0b
          ansible_aws_ssm_region: ap-southeast-2
          ansible_aws_ssm_bucket_name: "terraform-state.supersensory.com.au"
          ansible_python_interpreter: /usr/bin/python3
